/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Records the outcome of running a scenario
 */
export interface ScenarioExecutionResult {
  /**
   * Identifier of the scenario that was executed
   */
  scenario_id: string;
  /**
   * Timestamp-based run identifier
   */
  run_id: string;
  /**
   * ISO 8601 timestamp of execution start
   */
  executed_at: string;
  /**
   * Overall outcome of the scenario execution
   */
  status: "success" | "failure";
  /**
   * MCP tool names called during execution, in order
   */
  tools_called: string[];
  /**
   * Total execution time in milliseconds
   */
  execution_time_ms: number;
  /**
   * Details if status is 'failure'
   */
  failure_details?: {
    /**
     * Tool that caused the failure
     */
    failed_tool: string;
    /**
     * Error message from the failure
     */
    error_message: string;
    /**
     * Error code if available
     */
    error_code?: string;
    /**
     * Additional context about the failure
     */
    context: {
      [k: string]: unknown;
    };
    [k: string]: unknown;
  };
  /**
   * Resources created during scenario execution
   */
  resources_created: {
    /**
     * Type of resource created
     */
    type: "project" | "app" | "database" | "backup_schedule" | "domain" | "container" | "user";
    /**
     * Resource identifier (e.g., p-abc123, app-xyz789)
     */
    id: string;
    /**
     * Human-readable resource name
     */
    name?: string;
    [k: string]: unknown;
  }[];
  /**
   * Whether cleanup was attempted
   */
  cleanup_performed: boolean;
  /**
   * Errors encountered during cleanup
   */
  cleanup_errors?: string[];
  /**
   * Path to full execution log file
   */
  log_file_path?: string;
  [k: string]: unknown;
}
