/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Defines a test scenario that exercises MCP tools through natural language prompts
 */
export interface ScenarioDefinition {
  /**
   * Unique scenario identifier in kebab-case
   */
  id: string;
  /**
   * Human-readable scenario name
   */
  name: string;
  /**
   * Path to case study documentation (if applicable)
   */
  source?: string;
  /**
   * Prompts to send to Claude Code CLI in sequence
   *
   * @minItems 1
   */
  prompts: [string, ...string[]];
  /**
   * Outcome-based validation criteria
   */
  success_criteria: {
    [k: string]: unknown;
  };
  /**
   * Cleanup prompts for resource teardown
   */
  cleanup?: string[];
  /**
   * Optional: MCP tools expected to be called
   */
  expected_tools?: string[];
  /**
   * Categorization tags
   */
  tags?: string[];
  [k: string]: unknown;
}
