export interface AuthorizationRequestRecord {
  state: string;
  internalState: string;
  clientId: string;
  redirectUri: string;
  /** Client's PKCE code_challenge - used to verify client at /token */
  codeChallenge: string;
  codeChallengeMethod: 'S256';
  /**
   * Bridge's PKCE code_verifier for Mittwald relationship.
   * Generated by the bridge and sent to Mittwald at token exchange.
   * Per FR-005: MUST be non-empty and 43-128 characters per RFC 7636.
   */
  mittwaldCodeVerifier: string;
  scope: string;
  resource?: string;
  /**
   * Bridge-generated PKCE verifier used for the Mittwald leg of the flow.
   * Must be non-empty and 43-128 characters (RFC 7636).
   */
  mittwaldCodeVerifier: string;
  createdAt: number;
  expiresAt: number;
  /**
   * Whether this state has been consumed (used for single-use enforcement).
   * Optional for backward compatibility with existing records.
   */
  consumed?: boolean;
}

export interface AuthorizationGrantRecord {
  authorizationCode: string;
  clientId: string;
  redirectUri: string;
  /** Client's PKCE code_challenge - used to verify client at /token */
  codeChallenge: string;
  codeChallengeMethod: 'S256';
  /**
   * Bridge's PKCE code_verifier for Mittwald relationship.
   * Used when exchanging authorization code with Mittwald.
   */
  mittwaldCodeVerifier: string;
  scope: string;
  resource?: string;
  mittwaldAuthorizationCode: string;
  /**
   * Bridge-generated PKCE verifier to complete the Mittwald token exchange.
   * Copied from the authorization request for use during code exchange.
   */
  mittwaldCodeVerifier: string;
  mittwaldTokens?: MittwaldTokenResponse;
  createdAt: number;
  expiresAt: number;
  used: boolean;
  refreshToken?: string;
  refreshTokenExpiresAt?: number;
}

export interface MittwaldTokenResponse {
  access_token: string;
  token_type: string;
  expires_in: number;
  refresh_token?: string;
  scope?: string;
}

export interface ClientRegistrationRecord {
  clientId: string;
  clientSecret?: string;
  tokenEndpointAuthMethod: 'none' | 'client_secret_basic' | 'client_secret_post';
  redirectUris: string[];
  scope?: string;
  clientName?: string;
  registrationAccessToken: string;
  registrationClientUri: string;
  clientIdIssuedAt: number;
  clientSecretExpiresAt?: number;
  metadata?: Record<string, unknown>;
}

export interface StateStoreHealth {
  status: 'ok' | 'error';
  details?: Record<string, unknown>;
}

export interface StateStoreMetrics {
  implementation: string;
  ttlSeconds?: number;
  pendingAuthorizations: number;
  pendingGrants: number;
  registeredClients: number;
}

export interface StateStore {
  storeAuthorizationRequest(record: AuthorizationRequestRecord): Promise<void>;
  getAuthorizationRequestByInternalState(internalState: string): Promise<AuthorizationRequestRecord | null>;
  /**
   * Atomically retrieves and consumes the authorization request.
   * Implements single-use enforcement by deleting the record on read.
   * Returns null if the state is not found, already consumed, or expired.
   */
  getAndConsumeState(internalState: string): Promise<AuthorizationRequestRecord | null>;
  deleteAuthorizationRequestByInternalState(internalState: string): Promise<void>;
  storeAuthorizationGrant(record: AuthorizationGrantRecord): Promise<void>;
  getAuthorizationGrant(authorizationCode: string): Promise<AuthorizationGrantRecord | null>;
  updateAuthorizationGrant(record: AuthorizationGrantRecord): Promise<void>;
  deleteAuthorizationGrant(authorizationCode: string): Promise<void>;
  storeClientRegistration(record: ClientRegistrationRecord): Promise<void>;
  getClientRegistration(clientId: string): Promise<ClientRegistrationRecord | null>;
  deleteClientRegistration(clientId: string): Promise<void>;
  healthCheck(): Promise<StateStoreHealth>;
  getMetrics(): Promise<StateStoreMetrics>;
}
