/**
 * Parallel Validation Contracts
 *
 * Interfaces for comparing CLI spawn vs library outputs during migration.
 *
 * Location: tests/validation/parallel-validator.ts
 */

/**
 * Result of parallel validation (CLI spawn vs library call)
 *
 * Used to ensure 100% output parity before removing CLI spawning.
 */
export interface ValidationResult {
  /** Name of the MCP tool being validated */
  toolName: string;

  /** Whether outputs match (true = 100% parity) */
  passed: boolean;

  /** CLI spawn output */
  cliOutput: {
    /** CLI stdout (parsed JSON) */
    stdout: string;

    /** CLI stderr */
    stderr: string;

    /** CLI exit code */
    exitCode: number;

    /** CLI execution duration (milliseconds) */
    durationMs: number;
  };

  /** Library call output */
  libraryOutput: {
    /** Library result data */
    data: unknown;

    /** Library HTTP status */
    status: number;

    /** Library execution duration (milliseconds) */
    durationMs: number;
  };

  /** List of discrepancies (empty if passed = true) */
  discrepancies: Array<{
    /** Field path (e.g., "data.installations[0].name") */
    field: string;

    /** Value from CLI output */
    cliValue: unknown;

    /** Value from library output */
    libraryValue: unknown;

    /** Human-readable diff */
    diff: string;
  }>;
}

/**
 * Validate tool parity between CLI spawn and library call
 *
 * Executes the same operation via both methods and compares outputs.
 *
 * @param toolName - MCP tool name (e.g., "mittwald_app_list")
 * @param params - Tool parameters (projectId, etc.)
 * @returns Validation result with parity status and discrepancies
 */
export async function validateToolParity(
  toolName: string,
  params: Record<string, unknown>
): Promise<ValidationResult>;

/**
 * Validation report format (JSON output)
 *
 * Generated by validation suite for all tools.
 */
export interface ValidationReport {
  /** Timestamp of validation run */
  timestamp: string;

  /** Total tools validated */
  totalTools: number;

  /** Tools that passed validation */
  passedTools: number;

  /** Tools that failed validation */
  failedTools: number;

  /** Detailed results per tool */
  results: ValidationResult[];

  /** Summary statistics */
  summary: {
    /** Percentage of tools with 100% parity */
    parityRate: number;

    /** Average discrepancy count per tool */
    avgDiscrepancies: number;

    /** Total discrepancies across all tools */
    totalDiscrepancies: number;
  };
}
