#!/usr/bin/env npx tsx
/**
 * Generates context-flag-support.ts by scanning all tool definitions
 * and extracting which context flags each tool supports.
 *
 * Run: npx tsx scripts/generate-context-flag-map.ts
 */

import { readdir, readFile, writeFile } from 'node:fs/promises';
import { join, resolve } from 'node:path';

const TOOL_DEFINITIONS_DIR = 'src/constants/tool/mittwald-cli';
const OUTPUT_FILE = 'src/utils/context-flag-support.ts';

interface ContextFlagSupport {
  projectId: boolean;
  serverId: boolean;
  orgId: boolean;
}

interface ToolDefinition {
  name: string;
  inputSchema?: {
    properties?: Record<string, unknown>;
  };
}

/**
 * Recursively find all TypeScript files in a directory
 */
async function findTsFiles(dir: string): Promise<string[]> {
  const files: string[] = [];
  const entries = await readdir(dir, { withFileTypes: true });

  for (const entry of entries) {
    const fullPath = join(dir, entry.name);
    if (entry.isDirectory()) {
      const subFiles = await findTsFiles(fullPath);
      files.push(...subFiles);
    } else if (entry.name.endsWith('-cli.ts')) {
      files.push(fullPath);
    }
  }

  return files;
}

/**
 * Extract tool name and properties from a tool definition file
 */
async function extractToolDefinition(filePath: string): Promise<ToolDefinition | null> {
  const content = await readFile(filePath, 'utf8');

  // Extract tool name using regex
  const nameMatch = content.match(/name:\s*['"]([^'"]+)['"]/);
  if (!nameMatch) {
    return null;
  }

  const name = nameMatch[1];

  // Check for projectId, serverId, orgId in properties
  const hasProjectId = /properties:\s*\{[^}]*projectId\s*:/s.test(content);
  const hasServerId = /properties:\s*\{[^}]*serverId\s*:/s.test(content);
  const hasOrgId = /properties:\s*\{[^}]*orgId\s*:/s.test(content);

  return {
    name,
    inputSchema: {
      properties: {
        ...(hasProjectId && { projectId: true }),
        ...(hasServerId && { serverId: true }),
        ...(hasOrgId && { orgId: true }),
      }
    }
  };
}

/**
 * Generate the TypeScript source file content
 */
function generateSourceCode(tools: Map<string, ContextFlagSupport>): string {
  const sortedEntries = Array.from(tools.entries()).sort((a, b) => a[0].localeCompare(b[0]));

  const mapEntries = sortedEntries
    .map(([name, support]) => {
      const flags = [
        `projectId: ${support.projectId}`,
        `serverId: ${support.serverId}`,
        `orgId: ${support.orgId}`
      ].join(', ');
      return `  '${name}': { ${flags} }`;
    })
    .join(',\n');

  return `/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by: scripts/generate-context-flag-map.ts
 * Generated at: ${new Date().toISOString()}
 *
 * This file maps Mittwald CLI tool names to their supported context flags.
 * Used by session-aware-cli.ts to determine which flags to inject.
 */

export interface ContextFlagSupport {
  projectId: boolean;
  serverId: boolean;
  orgId: boolean;
}

/**
 * Map of tool names to their supported context flags.
 * Derived from each tool's inputSchema.properties.
 */
export const CONTEXT_FLAG_SUPPORT: Record<string, ContextFlagSupport> = {
${mapEntries}
};

/**
 * Get context flag support for a given tool.
 * Returns a safe default (no flags supported) if tool is not found.
 */
export function getContextFlagSupport(toolName: string): ContextFlagSupport {
  return CONTEXT_FLAG_SUPPORT[toolName] ?? {
    projectId: false,
    serverId: false,
    orgId: false
  };
}

/**
 * Check if a specific context flag is supported by a tool.
 */
export function supportsContextFlag(
  toolName: string,
  flag: keyof ContextFlagSupport
): boolean {
  return getContextFlagSupport(toolName)[flag];
}
`;
}

async function main(): Promise<void> {
  const rootDir = resolve(process.cwd());
  const toolsDir = join(rootDir, TOOL_DEFINITIONS_DIR);
  const outputPath = join(rootDir, OUTPUT_FILE);

  console.log(`Scanning tool definitions in: ${toolsDir}`);

  const tsFiles = await findTsFiles(toolsDir);
  console.log(`Found ${tsFiles.length} tool definition files`);

  const toolSupport = new Map<string, ContextFlagSupport>();
  let withProjectId = 0;
  let withServerId = 0;
  let withOrgId = 0;

  for (const file of tsFiles) {
    const definition = await extractToolDefinition(file);
    if (definition) {
      const props = definition.inputSchema?.properties ?? {};
      const support: ContextFlagSupport = {
        projectId: 'projectId' in props,
        serverId: 'serverId' in props,
        orgId: 'orgId' in props
      };
      toolSupport.set(definition.name, support);

      if (support.projectId) withProjectId++;
      if (support.serverId) withServerId++;
      if (support.orgId) withOrgId++;
    }
  }

  console.log(`\nContext flag support summary:`);
  console.log(`  Total tools: ${toolSupport.size}`);
  console.log(`  With projectId: ${withProjectId} (${((withProjectId / toolSupport.size) * 100).toFixed(1)}%)`);
  console.log(`  With serverId: ${withServerId} (${((withServerId / toolSupport.size) * 100).toFixed(1)}%)`);
  console.log(`  With orgId: ${withOrgId} (${((withOrgId / toolSupport.size) * 100).toFixed(1)}%)`);

  const sourceCode = generateSourceCode(toolSupport);
  await writeFile(outputPath, sourceCode, 'utf8');

  console.log(`\nGenerated: ${outputPath}`);
}

main().catch((error) => {
  console.error('Failed to generate context flag map:', error);
  process.exitCode = 1;
});
